- name: Downloading files

  vars:
    focal_dir: focal
    focal_name: focalgdm3.sh
    focal: wget https://github.com/PRATAP-KUMAR/focalgdm3/raw/master/focalgdm3.sh

  - name: Create focal dirctory
    file:
      state: directory
      path: focalgdm3.sh

    get_url:
      url: wget https://github.com/PRATAP-KUMAR/focalgdm3/raw/master/focalgdm3.sh
      dest: focal/focalgdm3.sh